### PR TITLE
Dummy Merge Request - Test CI Trigger

### PR DESCRIPTION
**Pull request by schuetzepaul**
This should test the automatic CI trigger

### CODE REVIEW

**Comment by simonspa** [comment]
...it does! :tada:

**Comment by simonspa** [comment]
now not anymore, because it's a `draft`?

**Comment by simonspa** [comment]
So what happens if you "un-draft" without pushing again?

**Comment by schuetzepaul** [comment]
It does checks again indeed

**Comment by simonspa** [comment]
Yes, it does! Cool.

**Comment by schuetzepaul** [comment]
It's this one...
```
on:                                                                                                                                                                                      
  pull_request:                                                                                                                                                                          
    types: [opened, reopened, edited, ready_for_review]                                                                                                                                  
```
explanation here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

Now, I thought that `edited` would be e.g. a new commit - seems like this isn't the case.

**Comment by simonspa** [comment]
But didn't it *not* trigger because it was in draft mode? Try pusing a new commit when not being in *draft*?

**Comment by schuetzepaul** [comment]
Mmh. Nothing yet.

**Pull request closed without merging**
