### PR TITLE
CSADigitizer: last threshold crossing for ToT

### PR DESCRIPTION
**Pull request by stephanlachnit**
This PR aims to add an option to allow to use the last threshold crossing in the ToT measurement to determine the ToT. This is the behavior on the MuPix10 and allows better precision in high noise to signal scenarios.

To demonstrate the difference, this plot was made in a high noise scenario (Fe55) with a MuPix10 parameterization:

new_tot_mode

The current implementation has two problems:
- no option to enable or disable the mode right now
- currently this is bound to the integration time, which is bad since we ideally want this to be a certain amount of time after the ToA, i.e. some max amounts of clock cycles where it stops

Regarding the second one:
I think it would be best to introduce two integration times: a ToA integration time, and a ToT integration time. First, we amplify the pulse only for the ToA integration time. If we get a signal, then we amplify again so that we end up at the ToT integration time.

The simpler alternative would be to just define a ToT integration time, and stop when `time - toa_time > tot_time`. The problem here is that we can't ensure that the pulse is amplified long enough (imagine the integration time is 1us and the ToT integration time 100ns, but the ToA time is 950ns). To prevent this we would need a relatively high base integration time.

Regarding the first one:
This behavior, no matter which option, should definitely be optional as is it costs some performance, and also maybe other chips don't have this behavior. I haven't run benchmarks (yet), but it felt not insignificant. With the first option, I propose this interface:
```config
tot_last_crossing = true
toa_integration_time = 1us
tot_integration_time = 1us
```
If `tot_last_crossing` is false, the interface would stay just as before.

For the second option, one can simply use
```config
last_crossing_integration_time = 1us
```
If this variable is set, the new mode is enabled, else it is not.

Any thoughts / feedback?

### CODE REVIEW

**Comment by stephanlachnit** [comment]
Performance numbers (10,000 runs):

New behavior:
```
(S) Executed 7 instantiations in 43 seconds, spending 89% of time in slowest instantiation CSADigitizer:detector
(I)  Module GeometryBuilderGeant4 took 0.0727533 seconds
(I)  Module DepositionGeant4 took 15.2367 seconds
(I)  Module ElectricFieldReader:detector took 0.0654382 seconds
(I)  Module GenericPropagation:detector took 11.5512 seconds
(I)  Module PulseTransfer:detector took 2.43689 seconds
(I)  Module CSADigitizer:detector took 237.633 seconds
(I)  Module ROOTObjectWriter took 0.552364 seconds
(S) Average processing time is 4 ms/event, event generation at 232 Hz
(S) This corresponds to a processing time of 32 ms/event per worker
```
Old behavior:
```
(S) Executed 7 instantiations in 38 seconds, spending 86% of time in slowest instantiation CSADigitizer:detector
(I)  Module GeometryBuilderGeant4 took 0.0656114 seconds
(I)  Module DepositionGeant4 took 13.2465 seconds
(I)  Module ElectricFieldReader:detector took 0.0303207 seconds
(I)  Module GenericPropagation:detector took 15.4272 seconds
(I)  Module PulseTransfer:detector took 2.29964 seconds
(I)  Module CSADigitizer:detector took 192.944 seconds
(I)  Module ROOTObjectWriter took 0.609226 seconds
(S) Average processing time is 4 ms/event, event generation at 266 Hz
(S) This corresponds to a processing time of 32 ms/event per worker
```

So the new behavior takes ~25% longer. Obviously this depends on the settings: with high noise, the earlier implementation sets the ToT too early, which wouldn't happen in lower noise cases. Also, the integration time was not "optimized" (3us, but the ToT never goes higher than 800ms). With the first implementation, one also saves some computing time by only amplifying for the ToA time if the signal doesn't cross the threshold (only 0.04% of the events create a hit).

**Comment by stephanlachnit** [comment]
So I played around with the first idea of the separate ToA and ToT integration times, it sounds nice at first but as far as I see it the pulse needs to be amplified from the beginning again if we cross the threshold, so it is potentially even worse than just having a longer base integration time.

**Comment by stephanlachnit** [comment]
> Is what you are describing here something similar to what is usually referred to "iToT" or integrated ToT? Summing up the different sections above threshold? Or really just returning the maximum ToT found in the event?

Yes, afaik it is the last crossing.

> I think it is interesting but we should be a bit careful not to add too many "small" features to the module - because every front-end in the end might require a slight tuning here and there...

Yes I can understand that. The MuPix10 does have some other features that wouldn't fit in here, for example a second threshold. I'm not sure if I will ever implemented everything, but just out of interest: if I would fork the module, would you be interested in having this upstream?

**Comment by simonspa** [comment]
> Yes I can understand that. The MuPix10 does have some other features that wouldn't fit in here, for example a second threshold.

Keep in mind that also the modularity of APSQ can provide you with some features - e.g. setting up two digitizer modules that process the same incoming PixelCharge objects with different thresholds and write the output to trees for a comparison/merging offline is done with two lines of config file:

```toml
[CSADigitizer]
output = "threshold1"
threshold = 800e

[CSADigitizer]
output = "threshold2"
threshold = 1200e
```

> I'm not sure if I will ever implemented everything, but just out of interest: if I would fork the module, would you be interested in having this upstream?

You mean a fully-specialized module for MuPix10? I haven't wrapped my head around this yet - let's see once we get there... :smile:

**Comment by stephanlachnit** [comment]
> > Yes I can understand that. The MuPix10 does have some other features that wouldn't fit in here, for example a second threshold.
> 
> Keep in mind that also the modularity of APSQ can provide you with some features - e.g. setting up two digitizer modules that process the same incoming PixelCharge objects with different thresholds and write the output to trees for a comparison/merging offline is done with two lines of config file:
> 
> ```toml
> [CSADigitizer]
> output = "threshold1"
> threshold = 800e
> 
> [CSADigitizer]
> output = "threshold2"
> threshold = 1200e
> ```

Ah thanks, I didn't know that.

> > I'm not sure if I will ever implemented everything, but just out of interest: if I would fork the module, would you be interested in having this upstream?
> 
> You mean a fully-specialized module for MuPix10? I haven't wrapped my head around this yet - let's see once we get there...

Yes, just in theory. E.g. the MuPix10 also has a ramp mode, which changes the threshold linearly after TS1 is latched, which would definitely not fit in this module (but it also is something that I don't need right now and probably exceeds the scope of my bachelor thesis). And another thing is that a colleague mentioned that the falling slope of the amplified pulse is independent of the charge, which also would require major rewrites of the module that are probably better suited in a separate one.

**Comment by stephanlachnit** [comment]
@simonspa The code is ready to review, I'm not entirely happy with the name `last_threshold_crossing_tot`.
I *think* the last commits is a bit more efficient by only assigning the `was_above_threshold` a new (hard-coded) value when it actually changes, but I'm not entirely sure and also it's harder to read.

**Comment by stephanlachnit** [comment]
I've been working on a new module for the MuPix10 today anyway, so this might not be used in the end after all. Depends on whether you want this or not.

**Pull request closed without merging**
