### PR TITLE
DepositionReader: add non-sequential read option

### PR DESCRIPTION
**Pull request by stephanlachnit**
As discussed in https://allpix-squared-forum.web.cern.ch/t/event-branch-in-depositionreader/156.

Do not merge, this is only a first draft.

### CODE REVIEW

**Comment by stephanlachnit** [comment]
@simonspa sorry for the delay, can be reviewed now.

**Comment by simonspa** [comment]
For reference, here the merge request on GitLab to run the full CI pipeline:
https://gitlab.cern.ch/allpix-squared/allpix-squared/-/merge_requests/419

There were two linter suggestions concerning the new string comparison, which I implemented directly.

**Comment by stephanlachnit** [comment]
Just a quick note: the `.c_str()` is necessary for this to work. Without it, it's just the same as the `==` operator. I think the trick here is that casting this into a C string will result in `detector\0\0`, and the comparison will stop at the first `\0`. That's why I said I think it's a bit hacky.

**Comment by stephanlachnit** [comment]
One idea to avoid this entirely is to just save it as a C string when reading. I can try that to satisfy the linter.

**Comment by simonspa** [comment]
You are right, I just realized this... :smile: For now I just told the linter to stop complaining. Feel free to fix it properly though!

**Comment by stephanlachnit** [comment]
Ahhhh I have an idea. I think the issue is in these lines:

https://github.com/allpix-squared/allpix-squared/blob/3d48b05fe50b0c2a1a826bff6442f9a08295837f/src/modules/DepositionReader/DepositionReaderModule.cpp#L426-L427

It gets casted into a std string with a fixed length, but the length is taken from the C string, which is one longer than. Adding a `-1` should fix it. I will give it a try.

**Comment by stephanlachnit** [comment]
@simonspa I tested the code now with both the python script and my own data, and I looks like it works (checked with the trace output as well).

I also changed the gitignore to exlcude `include/` and `share/` in the top level directory, since that currently isn't the case which makes git diffs a bit annoying when trying multiple rebuilds. Let me know what you think, I can also remove it again.

**Comment by simonspa** [comment]
Ah, nice catch with the ignored directories, thanks! Let me re-trigger the GitLab CI then. :)

**Comment by simonspa** [comment]
Thanks a lot, @stephanlachnit - merged via GitLab.

**Pull request merged**
