### PR TITLE
Draft: Add linter and cmake-linter to github ci

### PR DESCRIPTION
**Pull request by schuetzepaul**
Title says it all.

### CODE REVIEW

**Comment by simonspa** [comment]
Nice, thanks! I still don't fully understand how these Actions should be used - would it maybe make sense to run the linting (and format checks?) in a different "workflow"? Does that have any advantages over how we're doing it currently? :thinking:

**Comment by schuetzepaul** [comment]
I could test it. But I'm not sure whether it makes any difference, to be honest :D

**Comment by schuetzepaul** [comment]
If you now go to the "Checks" tab, it looks a bit different. It shouldn't have any impact though. We could of course run the formatting e.g. only on PRs that are ready for review, but I'm not sure whether this is what we want. Do you have any preference?

**Comment by simonspa** [comment]
:shrug: no preference really. I like the separation, it's a bit like the stages in GL. Let's keep it like it is and adjust as we go?

**Comment by simonspa** [comment]
So, looking good - will you open this on GitLab for merging?

**Pull request merged**
