### PR TITLE
WIP: Testing Pipeline Trigger for github

### PR DESCRIPTION
**Pull request by schuetzepaul**
Don't merge!
This should only test the pipeline/action trigger on opening a PR.

### CODE REVIEW

**Comment by simonspa** [comment]
:smirk:

**Comment by simonspa** [comment]
But is not triggered? Probably because the CI must already be in the repo for it to be triggered on pull request?

**Comment by schuetzepaul** [comment]
> Note: Workflows do not run on private base repositories when you open a pull request from a forked repository.

> When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.

> Workflows don't run on forked repositories by default. You must enable GitHub Actions in the Actions tab of the forked repository.

**Comment by schuetzepaul** [comment]
But that means that it should actually run on the base repository.

**Comment by simonspa** [comment]
Yes - it should run in the base repository. But the base repository has no CI defined, so nothing is run.

**Pull request merged**
