### PR TITLE
Allow Parsing of Scientific Notation

### PR DESCRIPTION
**Pull request by mmoanis**
Fix issue [#143](https://gitlab.cern.ch/allpix-squared/allpix-squared/issues/143) "Allow Parsing of Scientific Notation"

The actual problem is how we define zero. In the `Units::display` function, a zero is a number that is strictly less than the epsilon value for its type. 
[Epsilon](https://en.cppreference.com/w/cpp/types/numeric_limits/epsilon) is defined as the number next to 1 and since [floating point representation is not equally spaced](https://www.exploringbinary.com/the-spacing-of-binary-floating-point-numbers/) using the value of epsilon for comparing very small number fails.
The [suggested approach](https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/) is to scale the value of epsilon to the magnitude of the numbers being compared with the required precision.

This change scales the epsilon value with the value of the number being compared. But maybe we don't need this special case for zero at all. This will be much simpler.

### CODE REVIEW

**Comment by simonspa** [comment]
Thanks for digging into this.

@Koensw what do you think about abandoning the check for zero? Then we would have units printed along with zero values, which sometimes might even be favorable?

**Comment by Koensw** [comment]
Thanks for this PR! The only problem is that the best unit is pretty much undefined for zero. That might however be just fine, in that case we indeed get rid of the extra check.

**Comment by mmoanis** [comment]
Updated the patch. In case the input is zero, the first unit will be chosen.

**Comment by simonspa** [comment]
Great, thanks a lot!

GL MR: https://gitlab.cern.ch/allpix-squared/allpix-squared/merge_requests/207

**Comment by simonspa** [comment]
Had to adapt two of the module tests which were checking for regex with the old style of printing zeros.

**Pull request merged**
